application: lumx
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
# TODO Convert all directives to single app
# - url: /directives/(.+)
#   static_files: demo/directives/\1/index.html
#   upload: directives/\1/index.html

# TODO Remove once all directives are single app
- url: /services/notifications
  static_files: demo/services/notifications/index.html
  upload: services/notifications/index.html

- url: /demo
  static_dir: demo

- url: /js
  static_dir: js

- url: /build
  static_dir: build

- url: /libs
  static_dir: libs

- url: /fonts
  static_dir: fonts

- url: /app.js
  static_files: app.js
  upload: app.js
  mime_type: application/javascript

- url: /favicon.png
  static_files: favicon.png
  upload: favicon.png

- url: /.*
  static_files: index.html
  upload: index\.html
